// To do: 
// search bar text 

const plants = [
    {
        'Latin name': "Ammophila arenaria",
        'Dutch name': "Helmgras",
        'Main image': "images/Ammophila arenaria/Ammophila arenaria 1.JPG",
        'Sub images':["images/Ammophila arenaria/Ammophila arenaria 2.JPG","images/Ammophila arenaria/Ammophila arenaria 3.JPG","images/Ammophila arenaria/Ammophila arenaria 4.JPG","images/Ammophila arenaria/Ammophila arenaria 5.JPG",],
        "TYPE OF PLANT": [],
        "USE": [],
        "FLOWER COLOUR": [],
        "LEAF COLOUR": [],
        "FLOWERING PERIOD": [],
        "HEIGHT": [],
        "WIDTH": [],
        "SUNLIGHT": [],
        "GROUND TYPE": [],
        "MOISTURE LEVEL": [],
        "PH VALUE":[],
        "LOCATION":[],
        "WINTER FEATURES": [],
        "AUTUMN COLOURS": [],
        "FRUITS": [],
        "EDIBLE": [],
        "ORIGIN": [],
        "SPECIAL FEATURES":[],
        "PLANTING DENSITY":[],
        "AVERAGE PRICE P9 OR 10/12":[],
        "SCHOOLYEAR": [],
        "NOTE": []
    },
    {
        'Latin name': "Impatiens glandulifera",
        'Dutch name': "Reuzenbalsemien",
        'Main image': "images/Impatiens glandulifera/Impatiens glandulifera 1.JPG",
        'Sub images':["images/Impatiens glandulifera/Impatiens glandulifera 2.JPG","images/Impatiens glandulifera/Impatiens glandulifera 3.JPG","images/Impatiens glandulifera/Impatiens glandulifera 4.JPG","images/Impatiens glandulifera/Impatiens glandulifera 5.JPG","images/Impatiens glandulifera/Impatiens glandulifera 6.JPG","images/Impatiens glandulifera/Impatiens glandulifera 7.JPG"],
    },
    {
        'Latin name': "Iris pseudacorus",
        'Dutch name': "Gele lis",
        'Main image': "images/Iris pseudacorus/Iris pseudacorus 1.JPG",
        'Sub images':["images/Iris pseudacorus/Iris pseudacorus 2.JPG"],
    },
    {
        'Latin name': "Nuphar lutea",
        'Dutch name': "Gele plomp",
        'Main image': "images/Nuphar lutea/Nuphar lutea 1.JPG",
        'Sub images':["images/Nuphar lutea/Nuphar lutea 2.JPG","images/Nuphar lutea/Nuphar lutea 3.JPG","images/Nuphar lutea/Nuphar lutea 4.JPG","images/Nuphar lutea/Nuphar lutea 5.JPG"],
    },
    {
        'Latin name': "Populus x canescens",
        'Dutch name': "Grauwe abeel",
        'Main image': "images/Populus x canescens/Populus x canescens 1.JPG",
        'Sub images':["images/Populus x canescens/Populus x canescens 2.JPG","images/Populus x canescens/Populus x canescens 3.JPG","images/Populus x canescens/Populus x canescens 4.JPG","images/Populus x canescens/Populus x canescens 5.JPG","images/Populus x canescens/Populus x canescens 6.JPG","images/Populus x canescens/Populus x canescens 7.JPG","images/Populus x canescens/Populus x canescens 8.JPG"],
    },
    {
        'Latin name': "Taxodium distichum",
        'Dutch name': "Moerascipres",
        'Main image': "images/Taxodium distichum/Taxodium distichum 1.JPG",
        'Sub images':["images/Taxodium distichum/Taxodium distichum 2.JPG","images/Taxodium distichum/Taxodium distichum 3.JPG","images/Taxodium distichum/Taxodium distichum 4.JPG"],
    },

// HOUSEPLANTS

{
    'Latin name': "Adiantum raddianum 'Fragrans'",
    'Dutch name': "",
    'Main image': "houseplants/Adiantum raddianum 'Fragrans'/Adiantum raddianum 'Fragrans' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Adromischus cooperi",
    'Dutch name': "",
    'Main image': "houseplants/Adromischus cooperi/Adromischus cooperi 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Aechmea fasciata",
    'Dutch name': "",
    'Main image': "houseplants/Aechmea fasciata/Aechmea fasciata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia Bambino Pink Variegata",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia Bambino Pink Variegata/Alocasia Bambino Pink Variegata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Alocasia baginda",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia baginda/Alocasia baginda 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia Black Velvet Aurea Variegata",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia Black Velvet Aurea Variegata/Alocasia Black Velvet Aurea Variegata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Alocasia cuprea",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia cuprea/Alocasia cuprea 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia 'Jacklyn'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia 'Jacklyn'/Alocasia 'Jacklyn' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia 'Jacklyn Ghost Mint'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia 'Jacklyn Ghost Mint'/Alocasia 'Jacklyn Ghost Mint' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Alocasia longiloba 'albo'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia longiloba 'albo'/Alocasia longiloba 'albo' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia Longiloba 'Purple'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia Longiloba 'Purple'/Alocasia Longiloba 'Purple' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Alocasia macrorrhizos 'Albo-variegata'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia macrorrhizos 'Albo-variegata'/Alocasia macrorrhizos 'Albo-variegata' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia macrorrhizos variegata aurea",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia macrorrhizos variegata aurea/Alocasia macrorrhizos variegata aurea 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia micholitziana 'Frydek'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia micholitziana 'Frydek'/Alocasia micholitziana 'Frydek' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia micholitziana 'Frydek Variegata'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia micholitziana 'Frydek Variegata'/Alocasia micholitziana 'Frydek Variegata' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia 'Pseudo Sanderiana'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia 'Pseudo Sanderiana'/Alocasia 'Pseudo Sanderiana' 1.jpg",
    'HOUSEPLANTS': ["Houseplant"],
},
{
    'Latin name': "Alocasia 'Pseudo Sanderiana Aurea'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia 'Pseudo Sanderiana Aurea'/Alocasia 'Pseudo Sanderiana Aurea' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia reginula 'Ninja'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia reginula 'Ninja'/Alocasia reginula 'Ninja' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia reginula 'Ninja pink variegata'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia reginula 'Ninja pink variegata'/Alocasia reginula 'Ninja pink variegata' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Alocasia reginula 'Ninja tricolor'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia reginula 'Ninja tricolor'/Alocasia reginula 'Ninja tricolor' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia x amazonica",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia x amazonica/Alocasia x amazonica 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia amazonica 'Pink Polly'",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia amazonica 'Pink Polly'/Alocasia amazonica 'Pink Polly' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Alocasia zebrina",
    'Dutch name': "",
    'Main image': "houseplants/Alocasia zebrina/Alocasia zebrina 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Ananas comosus",
    'Dutch name': "",
    'Main image': "houseplants/Ananas comosus/Ananas comosus 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Anthurium crystallinum",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium crystallinum/Anthurium crystallinum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Anthurium crystallinum 'Silver Blush'",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium crystallinum 'Silver Blush'/Anthurium crystallinum 'Silver Blush' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium 'Delta Force'",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium 'Delta Force'/Anthurium 'Delta Force' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium forgetii",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium forgetii/Anthurium forgetii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Anthurium luxurians",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium luxurians/Anthurium luxurians 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium papillilaminum × 'Dark Phoenix'",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium papillilaminum × 'Dark Phoenix'/Anthurium papillilaminum × 'Dark Phoenix' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium 'Queen of Hearts'",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium 'Queen of Hearts'/Anthurium 'Queen of Hearts' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium regale",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium regale/Anthurium regale 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium veitchii",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium veitchii/Anthurium veitchii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Anthurium vittarifolium",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium vittarifolium/Anthurium vittarifolium 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Anthurium Vittarifolium Variegata",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium Vittarifolium Variegata/Anthurium Vittarifolium Variegata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Anthurium warocqueanum",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium warocqueanum/Anthurium warocqueanum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Anthurium wendlingeri",
    'Dutch name': "",
    'Main image': "houseplants/Anthurium wendlingeri/Anthurium wendlingeri 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Asparagus setaceus",
    'Dutch name': "",
    'Main image': "houseplants/Asparagus setaceus/Asparagus setaceus 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Begonia 'Autumn Ember'",
    'Dutch name': "",
    'Main image': "houseplants/Begonia 'Autumn Ember'/Begonia 'Autumn Ember' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Begonia ferox",
    'Dutch name': "",
    'Main image': "houseplants/Begonia ferox/Begonia ferox 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Begonia maculata 'Black Forest'",
    'Dutch name': "",
    'Main image': "houseplants/Begonia maculata 'Black Forest'/Begonia maculata 'Black Forest' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Caladium bicolor 'Pink Beauty'",
    'Dutch name': "",
    'Main image': "houseplants/Caladium bicolor 'Pink Beauty'/Caladium bicolor 'Pink Beauty' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Caladium bicolor 'White Christmas'",
    'Dutch name': "",
    'Main image': "houseplants/Caladium bicolor 'White Christmas'/Caladium bicolor 'White Christmas' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Chlorophytum comosum 'Variegatum'",
    'Dutch name': "",
    'Main image': "houseplants/Chlorophytum comosum 'Variegatum'/Chlorophytum comosum 'Variegatum' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Cleistocactus colademononis",
    'Dutch name': "",
    'Main image': "houseplants/Cleistocactus colademononis/Cleistocactus colademononis 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Cleistocactus strausii",
    'Dutch name': "",
    'Main image': "houseplants/Cleistocactus strausii/Cleistocactus strausii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Crassula marnieriana",
    'Dutch name': "",
    'Main image': "houseplants/Crassula marnieriana/Crassula marnieriana 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Crassula mesembryanthemoides 'tenelli'",
    'Dutch name': "",
    'Main image': "houseplants/Crassula mesembryanthemoides 'tenelli'/Crassula mesembryanthemoides 'tenelli' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Crassula ovata 'Gollum'",
    'Dutch name': "",
    'Main image': "houseplants/Crassula ovata 'Gollum'/Crassula ovata 'Gollum' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Cryptosperma johnstonii",
    'Dutch name': "",
    'Main image': "houseplants/Cryptosperma johnstonii/Cryptosperma johnstonii 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Dionaea muscipula",
    'Dutch name': "",
    'Main image': "houseplants/Dionaea muscipula/Dionaea muscipula 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Dracaena marginata",
    'Dutch name': "",
    'Main image': "houseplants/Dracaena marginata/Dracaena marginata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Dracaena sanderiana",
    'Dutch name': "",
    'Main image': "houseplants/Dracaena sanderiana/Dracaena sanderiana 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Dracaena trifasciata 'Laurentii'",
    'Dutch name': "",
    'Main image': "houseplants/Dracaena trifasciata 'Laurentii'/Dracaena trifasciata 'Laurentii' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Epipremnum aureum",
    'Dutch name': "",
    'Main image': "houseplants/Epipremnum aureum/Epipremnum aureum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Epipremnum aureum 'Manjula'",
    'Dutch name': "",
    'Main image': "houseplants/Epipremnum aureum 'Manjula'/Epipremnum aureum 'Manjula' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Epipremnum aureum 'Marble Queen'",
    'Dutch name': "",
    'Main image': "houseplants/Epipremnum aureum 'Marble Queen'/Epipremnum aureum 'Marble Queen' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Epipremnum aureum 'Neon'",
    'Dutch name': "",
    'Main image': "houseplants/Epipremnum aureum 'Neon'/Epipremnum aureum 'Neon' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Epipremnum pinnatum 'Albo-Variegata'",
    'Dutch name': "",
    'Main image': "houseplants/Epipremnum pinnatum 'Albo-Variegata'/Epipremnum pinnatum 'Albo-Variegata' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Euphorbia trigona",
    'Dutch name': "",
    'Main image': "houseplants/Euphorbia trigona/Euphorbia trigona 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Ficus macrocarpa",
    'Dutch name': "",
    'Main image': "houseplants/Ficus macrocarpa/Ficus macrocarpa 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Gasteria pillansii Kensit",
    'Dutch name': "",
    'Main image': "houseplants/Gasteria pillansii Kensit/Gasteria pillansii Kensit 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Goeppertia kegeljanii",
    'Dutch name': "",
    'Main image': "houseplants/Goeppertia kegeljanii/Goeppertia kegeljanii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Gymnocalycium mihanovichii var. friedrichii",
    'Dutch name': "",
    'Main image': "houseplants/Gymnocalycium mihanovichii var. friedrichii/Gymnocalycium mihanovichii var. friedrichii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Haworthia cooperi",
    'Dutch name': "",
    'Main image': "houseplants/Haworthia cooperi/Haworthia cooperi 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Haworthia 'Universe'",
    'Dutch name': "",
    'Main image': "houseplants/Haworthia 'Universe'/Haworthia 'Universe' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Heptapleurum arboricola 'Variegata'",
    'Dutch name': "",
    'Main image': "houseplants/Heptapleurum arboricola 'Variegata'/Heptapleurum arboricola 'Variegata' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Hemionitis arifolia",
    'Dutch name': "",
    'Main image': "houseplants/Hemionitis arifolia/Hemionitis arifolia 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Hoya kerrii",
    'Dutch name': "",
    'Main image': "houseplants/Hoya kerrii/Hoya kerrii 1.JPG",
    'Sub images':["houseplants/Hoya kerrii/Hoya kerrii 2.JPG", "houseplants/Hoya kerrii/Hoya kerrii 3.JPG", "houseplants/Hoya kerrii/Hoya kerrii 4.JPG", "houseplants/Hoya kerrii/Hoya kerrii 5.JPG", "houseplants/Hoya kerrii/Hoya kerrii 6.JPG", "houseplants/Hoya kerrii/Hoya kerrii 7.JPG", "houseplants/Hoya kerrii/Hoya kerrii 8.JPG", ],
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Hylocereus undatus",
    'Dutch name': "",
    'Main image': "houseplants/Hylocereus undatus/Hylocereus undatus 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Hypoestes phyllostachya",
    'Dutch name': "",
    'Main image': "houseplants/Hypoestes phyllostachya/Hypoestes phyllostachya 1.JPG",
    'Sub images':["images/Hypoestes phyllostachya/Hypoestes phyllostachya 2.JPG"],
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Kalanchoe marmorata 'Partridge'",
    'Dutch name': "",
    'Main image': "houseplants/Kalanchoe marmorata 'Partridge'/Kalanchoe marmorata 'Partridge' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Licuala cordata",
    'Dutch name': "",
    'Main image': "houseplants/Licuala cordata/Licuala cordata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Lithops green",
    'Dutch name': "",
    'Main image': "houseplants/Lithops green/Lithops green 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Lithops grey",
    'Dutch name': "",
    'Main image': "houseplants/Lithops grey/Lithops grey 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Lithops hallii cv green",
    'Dutch name': "",
    'Main image': "houseplants/Lithops hallii cv green/Lithops hallii cv green 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Lithops hookeri var. marginata",
    'Dutch name': "",
    'Main image': "houseplants/Lithops hookeri var. marginata/Lithops hookeri var. marginata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Lithops red",
    'Dutch name': "",
    'Main image': "houseplants/Lithops red/Lithops red 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Lophophora williamsii",
    'Dutch name': "",
    'Main image': "houseplants/Lophophora williamsii/Lophophora williamsii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Mammillaria prolifera",
    'Dutch name': "",
    'Main image': "houseplants/Mammillaria prolifera/Mammillaria prolifera 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Maranta leuconeura var. kerchoveana",
    'Dutch name': "",
    'Main image': "houseplants/Maranta leuconeura var. kerchoveana/Maranta leuconeura var. kerchoveana 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Maranta leuconeura var. kerchoveana variegata",
    'Dutch name': "",
    'Main image': "houseplants/Maranta leuconeura var. kerchoveana variegata/Maranta leuconeura var. kerchoveana variegata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Monstera adansonii",
    'Dutch name': "",
    'Main image': "houseplants/Monstera adansonii/Monstera adansonii 1.JPG",
    'Sub images':["images/Monstera adansonii/Monstera adansonii 2.JPG"],
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Monstera deliciosa",
    'Dutch name': "",
    'Main image': "houseplants/Monstera deliciosa/Monstera deliciosa 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Monstera deliciosa 'Albo Borsigiana'",
    'Dutch name': "",
    'Main image': "houseplants/Monstera deliciosa 'Albo Borsigiana'/Monstera deliciosa 'Albo Borsigiana' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Monstera deliciosa 'Burle Marx Flame'",
    'Dutch name': "",
    'Main image': "houseplants/Monstera deliciosa 'Burle Marx Flame'/Monstera deliciosa 'Burle Marx Flame' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Monstera deliciosa 'Devil Monster'",
    'Dutch name': "",
    'Main image': "houseplants/Monstera deliciosa 'Devil Monster'/Monstera deliciosa 'Devil Monster' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
    'OTHER': ["Way too expensive for now."],
},
{
    'Latin name': "Monstera deliciosa 'Thai Constellation'",
    'Dutch name': "",
    'Main image': "houseplants/Monstera deliciosa 'Thai Constellation'/Monstera deliciosa 'Thai Constellation' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Monstera dubia",
    'Dutch name': "",
    'Main image': "houseplants/Monstera dubia/Monstera dubia 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Monstera 'Esqueleto'",
    'Dutch name': "",
    'Main image': "houseplants/Monstera 'Esqueleto'/Monstera 'Esqueleto' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Monstera obliqua",
    'Dutch name': "",
    'Main image': "houseplants/Monstera obliqua/Monstera obliqua 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Musa Florida Variegata",
    'Dutch name': "",
    'Main image': "houseplants/Musa Florida Variegata/Musa Florida Variegata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Musa x paradisiaca 'Ae-Ae'",
    'Dutch name': "",
    'Main image': "houseplants/Musa x paradisiaca 'Ae-Ae'/Musa x paradisiaca 'Ae-Ae' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Nepenthes albomarginata",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes albomarginata/Nepenthes albomarginata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Nepenthes albomarginata 'Penang'",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes albomarginata 'Penang'/Nepenthes albomarginata 'Penang' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Nepenthes edwardsiana",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes edwardsiana/Nepenthes edwardsiana 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Nepenthes 'Gaya'",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes 'Gaya'/Nepenthes 'Gaya' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Nepenthes 'Rokko x Gentle'",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes 'Rokko x Gentle'/Nepenthes 'Rokko x Gentle' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Nepenthes hamata",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes hamata/Nepenthes hamata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Nepenthes x ventrata",
    'Dutch name': "",
    'Main image': "houseplants/Nepenthes x ventrata/Nepenthes x ventrata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Nephrolepis exaltata",
    'Dutch name': "",
    'Main image': "houseplants/Nephrolepis exaltata/Nephrolepis exaltata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Oncidium",
    'Dutch name': "",
    'Main image': "houseplants/Oncidium/Oncidium 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Oncidium 'Yellow'",
    'Dutch name': "",
    'Main image': "houseplants/Oncidium 'Yellow'/Oncidium 'Yellow' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Opuntia microdasys var. albispina",
    'Dutch name': "",
    'Main image': "houseplants/Opuntia microdasys var. albispina/Opuntia microdasys var. albispina 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Opuntia monacantha f. monstruosa variegata",
    'Dutch name': "",
    'Main image': "houseplants/Opuntia monacantha f. monstruosa variegata/Opuntia monacantha f. monstruosa variegata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Oxalis triangularis",
    'Dutch name': "",
    'Main image': "houseplants/Oxalis triangularis/Oxalis triangularis 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Pachycereus pringlei",
    'Dutch name': "",
    'Main image': "houseplants/Pachycereus pringlei/Pachycereus pringlei 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Peperomia albovittata 'Rana Verde'",
    'Dutch name': "",
    'Main image': "houseplants/Peperomia albovittata 'Rana Verde'/Peperomia albovittata 'Rana Verde' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Phalaenopsis",
    'Dutch name': "",
    'Main image': "houseplants/Phalaenopsis/Phalaenopsis 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron billietiae",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron billietiae/Philodendron billietiae 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron billietiae Variegata",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron billietiae Variegata/Philodendron billietiae Variegata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
    'OTHER': ["Way too expensive rigth now"],
},
{
    'Latin name': "Philodendron bipinnatifidum 'Choco Empress'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron bipinnatifidum 'Choco Empress'/Philodendron bipinnatifidum 'Choco Empress' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron 'Burle Marx variegata'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron 'Burle Marx variegata'/Philodendron 'Burle Marx variegata' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron campii",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron campii/Philodendron campii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron elegans",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron elegans/Philodendron elegans 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron erubescens 'Pink Princess'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron erubescens 'Pink Princess'/Philodendron erubescens 'Pink Princess' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron erubescens 'Prince of Orange'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron erubescens 'Prince of Orange'/Philodendron erubescens 'Prince of Orange' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron erubescens 'Strawberry Shake'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron erubescens 'Strawberry Shake'/Philodendron erubescens 'Strawberry Shake' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron erubescens 'White Wizard'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron erubescens 'White Wizard'/Philodendron erubescens 'White Wizard' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron esmeraldense",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron esmeraldense/Philodendron esmeraldense 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron 'Florida Bronze'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron 'Florida Bronze'/Philodendron 'Florida Bronze' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron gloriosum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron gloriosum/Philodendron gloriosum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron Gloriosum Variegata",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron Gloriosum Variegata/Philodendron Gloriosum Variegata 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron gloriosum x melanochrysum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron gloriosum x melanochrysum/Philodendron gloriosum x melanochrysum 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron hastatum 'Silver Queen'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron hastatum 'Silver Queen'/Philodendron hastatum 'Silver Queen' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron hederaceum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron hederaceum/Philodendron hederaceum 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron hederaceum 'Micans f. pink variegatum'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron hederaceum 'Micans f. pink variegatum'/Philodendron hederaceum 'Micans f. pink variegatum' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron hederaceum var. hederaceum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron hederaceum var. hederaceum/Philodendron hederaceum var. hederaceum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron 'Snowdrift'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron 'Snowdrift'/Philodendron 'Snowdrift' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron longilobatum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron longilobatum/Philodendron longilobatum 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron mayoi",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron mayoi/Philodendron mayoi 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron melanochrysum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron melanochrysum/Philodendron melanochrysum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron patriciae Croat",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron patriciae Croat/Philodendron patriciae Croat 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron plowmanii",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron plowmanii/Philodendron plowmanii 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron 'Ring of Fire'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron 'Ring of Fire'/Philodendron 'Ring of Fire' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron rubrijuvenile 'El Choco Red'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron rubrijuvenile 'El Choco Red'/Philodendron rubrijuvenile 'El Choco Red' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron spiritus-sancti",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron spiritus-sancti/Philodendron spiritus-sancti 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Philodendron squamiferum x pedatum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron squamiferum x pedatum/Philodendron squamiferum x pedatum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron squamiferum x pedatum 'Florida Ghost'",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron squamiferum x pedatum 'Florida Ghost'/Philodendron squamiferum x pedatum 'Florida Ghost' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron tortum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron tortum/Philodendron tortum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron verrucosum",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron verrucosum/Philodendron verrucosum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Philodendron x joepii",
    'Dutch name': "",
    'Main image': "houseplants/Philodendron x joepii/Philodendron x joepii 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Pilea peperomioides",
    'Dutch name': "",
    'Main image': "houseplants/Pilea peperomioides/Pilea peperomioides 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Pilosocereus pachycladus",
    'Dutch name': "",
    'Main image': "houseplants/Pilosocereus pachycladus/Pilosocereus pachycladus 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Platycerium bifurcatum",
    'Dutch name': "",
    'Main image': "houseplants/Platycerium bifurcatum/Platycerium bifurcatum 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Pleiospilos nelii",
    'Dutch name': "",
    'Main image': "houseplants/Pleiospilos nelii/Pleiospilos nelii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Rhaphidophora foraminifera",
    'Dutch name': "",
    'Main image': "houseplants/Rhaphidophora foraminifera/Rhaphidophora foraminifera 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Rhaphidophora tetrasperma",
    'Dutch name': "",
    'Main image': "houseplants/Rhaphidophora tetrasperma/Rhaphidophora tetrasperma 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Rhipsalis paradoxa",
    'Dutch name': "",
    'Main image': "houseplants/Rhipsalis paradoxa/Rhipsalis paradoxa 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Salvinia minima",
    'Dutch name': "",
    'Main image': "houseplants/Salvinia minima/Salvinia minima 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Sarracenia flava",
    'Dutch name': "",
    'Main image': "houseplants/Sarracenia flava/Sarracenia flava 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Sarracenia purpurea var. heterophylla",
    'Dutch name': "",
    'Main image': "houseplants/Sarracenia purpurea var. heterophylla/Sarracenia purpurea var. heterophylla 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Scindapsus pictus",
    'Dutch name': "",
    'Main image': "houseplants/Scindapsus pictus/Scindapsus pictus 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Sedum morganianum 'Burrito'",
    'Dutch name': "",
    'Main image': "houseplants/Sedum morganianum 'Burrito'/Sedum morganianum 'Burrito' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Sempervivum calcareum 'Grigg's Surprise'",
    'Dutch name': "",
    'Main image': "houseplants/Sempervivum calcareum 'Grigg's Surprise'/Sempervivum calcareum 'Grigg's Surprise' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Sinningia speciosa",
    'Dutch name': "",
    'Main image': "houseplants/Sinningia speciosa/Sinningia speciosa 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Soleirolia soleirolii",
    'Dutch name': "",
    'Main image': "houseplants/Soleirolia soleirolii/Soleirolia soleirolii 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Spathiphyllum wallisii",
    'Dutch name': "",
    'Main image': "houseplants/Spathiphyllum wallisii/Spathiphyllum wallisii 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Stephania erecta",
    'Dutch name': "",
    'Main image': "houseplants/Stephania erecta/Stephania erecta 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Syngonium podophyllum 'Neon Robusta'",
    'Dutch name': "",
    'Main image': "houseplants/Syngonium podophyllum 'Neon Robusta'/Syngonium podophyllum 'Neon Robusta' 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Thaumatophyllum bipinnatifidum",
    'Dutch name': "",
    'Main image': "houseplants/Thaumatophyllum bipinnatifidum/Thaumatophyllum bipinnatifidum 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Thaumatophyllum bipinnatifidum 'Shangri-La'",
    'Dutch name': "",
    'Main image': "houseplants/Thaumatophyllum bipinnatifidum 'Shangri-La'/Thaumatophyllum bipinnatifidum 'Shangri-La' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Tillandsia ionantha",
    'Dutch name': "",
    'Main image': "houseplants/Tillandsia ionantha/Tillandsia ionantha 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Tillandsia streptophylla",
    'Dutch name': "",
    'Main image': "houseplants/Tillandsia streptophylla/Tillandsia streptophylla 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Tillandsia usneoides",
    'Dutch name': "",
    'Main image': "houseplants/Tillandsia usneoides/Tillandsia usneoides 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Tradescantia fluminensis 'Nanouk'",
    'Dutch name': "",
    'Main image': "houseplants/Tradescantia fluminensis 'Nanouk'/Tradescantia fluminensis 'Nanouk' 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},
{
    'Latin name': "Victoria amazonica",
    'Dutch name': "",
    'Main image': "houseplants/Victoria amazonica/Victoria amazonica 1.jpg",
    'HOUSEPLANTS': ["Houseplant", "Wishlist"],
},
{
    'Latin name': "Xanthosoma albo variegata",
    'Dutch name': "",
    'Main image': "houseplants/Xanthosoma albo variegata/Xanthosoma albo variegata 1.JPG",
    'HOUSEPLANTS': ["Houseplant", "My houseplants"],
},

// PLACEHOLDER

    {
        'Latin name': "Placeholder",
        'Dutch name': "text",
        'Main image': "images/text/text 1.JPG",
    },
];
